# SIMPLIFIA Workflow: Inbox Autopilot (Triagem + Draft)
# Pack: WhatsApp Neg칩cios
# Version: 1.0.0

id: wf_001_inbox_triage
name: "Inbox Autopilot"
description: "Classifica mensagens, extrai dados e gera resposta em rascunho"
version: "1.0.0"

trigger:
  type: message_in
  channels: [whatsapp]

steps:
  - id: extract_customer
    type: extract
    description: "Extrai ou cria registro do cliente"
    config:
      fields:
        - phone: "{{message.from}}"
        - name: "{{message.sender_name}}"
      upsert: true
      table: customers

  - id: classify_intent
    type: ai_classify
    description: "Classifica a inten칞칚o da mensagem"
    config:
      model: default
      categories:
        - id: orcamento
          description: "Pedido de pre칞o, valor, or칞amento"
          keywords: [pre칞o, valor, quanto, or칞amento, custa, tabela]
        - id: agendamento
          description: "Quer marcar hor치rio, agendar"
          keywords: [agendar, marcar, hor치rio, agenda, dispon칤vel, vaga]
        - id: duvida
          description: "Pergunta geral, informa칞칚o"
          keywords: [como, onde, qual, pode, tem, faz, funciona]
        - id: reclamacao
          description: "Problema, insatisfa칞칚o"
          keywords: [problema, reclama칞칚o, n칚o gostei, defeito, errado, p칠ssimo]
        - id: elogio
          description: "Feedback positivo"
          keywords: [obrigado, excelente, adorei, perfeito, 칩timo, maravilhoso]
      output: intent

  - id: extract_data
    type: ai_extract
    description: "Extrai dados estruturados da mensagem"
    config:
      model: default
      fields:
        - name: nome_cliente
          type: string
          description: "Nome do cliente se mencionado"
        - name: servico
          type: string
          description: "Servi칞o solicitado"
        - name: urgencia
          type: enum
          values: [baixa, media, alta]
          description: "Urg칡ncia baseada no tom"
        - name: data_preferida
          type: date
          description: "Data mencionada se houver"
        - name: localizacao
          type: string
          description: "Bairro ou cidade se mencionado"
      output: extracted_data

  - id: select_tone
    type: lookup
    description: "Seleciona tom de resposta baseado nas regras"
    config:
      file: "rules/tone_profiles.json"
      key: "{{config.default_tone}}"
      fallback: "educado"
      output: tone

  - id: generate_draft
    type: ai_generate
    description: "Gera rascunho de resposta"
    config:
      model: default
      prompt_template: |
        Contexto:
        - Neg칩cio: {{config.business_name}}
        - Inten칞칚o: {{intent}}
        - Tom: {{tone}}
        - Dados extra칤dos: {{extracted_data}}
        
        Mensagem recebida:
        {{message.text}}
        
        Gere uma resposta {{tone}} para esta mensagem.
        Seja breve (m치ximo 3 par치grafos).
        Inclua pr칩ximo passo claro.
      output: draft_response

  - id: save_interaction
    type: db_insert
    description: "Salva intera칞칚o no banco"
    config:
      table: interactions
      data:
        customer_id: "{{customer.id}}"
        pack_id: "whatsapp"
        workflow_id: "wf_001_inbox_triage"
        direction: "inbound"
        message_preview: "{{message.text | truncate(100)}}"
        intent: "{{intent}}"
        intent_confidence: "{{intent_confidence}}"
        status: "pending"
        draft_response: "{{draft_response}}"

  - id: notify_user
    type: notification
    description: "Notifica usu치rio sobre novo draft"
    config:
      title: "游닓 Nova mensagem ({{intent}})"
      body: "{{message.text | truncate(50)}}..."
      action: "review_draft"
      data:
        interaction_id: "{{interaction.id}}"

output:
  interaction_id: "{{interaction.id}}"
  intent: "{{intent}}"
  draft: "{{draft_response}}"
  status: "draft_ready"
